[package]
name = "rust-rogue"
version = "0.1.0"
authors = ["Galen Palmer <palmergs@gmail.com>"]

[dependencies]
rand = "0.3.9"
tcod = { version = "0.11", features = [ "rustc-serialize" ] }
rustc-serialize = "0.3"
